### PR TITLE
WIP: Display (& Select) Side Dishes

### PR DESCRIPTION
**Pull request by lgiesen**
@MarcelRe9 Please check, why the date is not displayed correctly.

This is how the side dishes look:
Screenshot 2023-01-20 at 17 09 21

### CODE REVIEW

**Comment by martenjostmann** [comment]
@lgiesen Maybe display the side dishes only as a list without the images

**Comment by lgiesen** [comment]
> Also the date is not important for the side dishes

The date is not included for the side dishes.

**Comment by MarcelRe9** [comment]
@lgiesen Date should be fixed now. See: #203

**Comment by erikzimmermann** [comment]
> > @lgiesen Maybe display the side dishes only as a list without the images
> 
> 
> 
> I like the images and would like to keep them.
> 
> 

I'd prefer having a smaller more compact popup for side dishes where you can select them easier. 

Also, it would be very nice if the prices of main and side dish are summed up to compare it with your card balance.

**Comment by lgiesen** [comment]
> > > @lgiesen Maybe display the side dishes only as a list without the images
> > 
> > 
> > I like the images and would like to keep them.
> 
> I'd prefer having a smaller more compact popup for side dishes where you can select them easier.
> 
> Also, it would be very nice if the prices of main and side dish are summed up to compare it with your card balance.

Since I use the main & side dishes as one component, it would be a little more complicated to implement the sum of the side dish and main dish. Since 1€ is added on top of the dish price, it would still cover any side dishes because all/most of them cost under 1€. Nevertheless, nice idea!

**Comment by lgiesen** [comment]
Screenshot 2023-01-21 at 13 53 19

**Comment by martenjostmann** [comment]
> Screenshot 2023-01-21 at 13 53 19

How should the selection process look like? Currently it is not obvious that the user can click on the side dishes. Also the most recommendable side dish should be highlighted.

**Comment by martenjostmann** [comment]
@lgiesen See #210 for api changes

**Comment by lgiesen** [comment]
The weekday does not work (in Firefox at least). @MarcelRe9, could you take a look at it?

Screenshot 2023-01-22 at 10 38 18

**Comment by lgiesen** [comment]
> > Screenshot 2023-01-21 at 13 53 19
> 
> How should the selection process look like? Currently it is not obvious that the user can click on the side dishes. Also the most recommendable side dish should be highlighted.

How should the selection feature look like? We don't have a selection API call, so what should the frontend do?

**Comment by MarcelRe9** [comment]
> The weekday does not work (in Firefox at least). @MarcelRe9, could you take a look at it?
> 
> Screenshot 2023-01-22 at 10 38 18

Should be fixed now

**Pull request merged**
