### PR TITLE
Select & Display Side Dishes

### PR DESCRIPTION
**Pull request by lgiesen**
#204

### CODE REVIEW

**Comment by lgiesen** [comment]
- [ ] display selected dishes in recommendation overview
- [ ] frequently selected together in side-dish dialog
- [ ] :bug: update of recommendation is not correct -> item[0].mensa not defined

**Comment by lgiesen** [comment]
Screenshot 2023-01-24 at 14 05 45

**Comment by lgiesen** [comment]
💡 Feature idea: calculate total costs of all side dishes and main dish

**Comment by martenjostmann** [comment]
Looks good 👍. Have a deeper look at it later. When you have time you can also implement the total costs :)

**Comment by erikzimmermann** [comment]
> Screenshot 2023-01-24 at 14 05 45

I really like that card design including side dishes 👍🏻 

Maybe a few little things:
- For me the "+" appears a bit large and not correctly in position when comparing it to the stars above.
- Also, when re-selecting side dishes the previous values are not loaded and one cannot remove the current selection.

**Comment by lgiesen** [comment]
> > Screenshot 2023-01-24 at 14 05 45
> 
> I really like that card design including side dishes 👍🏻
> 
> Maybe a few little things:
> 
>     * For me the "+" appears a bit large and not correctly in position when comparing it to the stars above.
> 
>     * Also, when re-selecting side dishes the previous values are not loaded and one cannot remove the current selection.



> > Screenshot 2023-01-24 at 14 05 45
> 
> I really like that card design including side dishes 👍🏻
> 
> Maybe a few little things:
> 
>     * For me the "+" appears a bit large and not correctly in position when comparing it to the stars above.
> 
>     * Also, when re-selecting side dishes the previous values are not loaded and one cannot remove the current selection.

Good points. I'll have a look at these bugs probably after the examination phase and hence after the official course deadline.

**Comment by martenjostmann** [comment]
I have added a star to indicate the most picked side dish. @lgiesen. The star might look better on the right site of the list but the property right doesn't work here. Do you now how to fix this? Also the sided are now preselected
grafik

**Pull request merged**
