### PR TITLE
Fix recommender without dishes

### PR DESCRIPTION
**Pull request by erikzimmermann**
Tested and working.

@lgiesen
The endpoint `get_week_recommendation` looks like that now if one day cannot provide a dish.
```json
[
    {},
    {
        "dish": {
            "id": 178,
            "categories": [],
            "additives": [],
            "allergies": [],
            "main": true,
            "name": "Pommes frites große Portion: 1,40€ / 2,10€",
            "url": "https://www.kochwiki.org/images/thumb/c/c4/H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg/1200px-H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg"
        },
        "ext_ratings": {
            "id": 294,
            "rating_avg": "4.6",
            "rating_count": 121
        },
        "user_ratings": [],
        "mensa": {
            "id": 10,
            "name": "Mensa am Ring",
            "city": "Münster",
            "street": "Domagkstr.",
            "houseNumber": "61",
            "zipCode": 48149,
            "startTime": "11:30:00",
            "endTime": "14:00:00"
        },
        "date": "2022-12-20",
        "priceStudent": "0.70",
        "priceEmployee": "1.05"
    },
    {
        "dish": {
            "id": 178,
            "categories": [],
            "additives": [],
            "allergies": [],
            "main": true,
            "name": "Pommes frites große Portion: 1,40€ / 2,10€",
            "url": "https://www.kochwiki.org/images/thumb/c/c4/H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg/1200px-H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg"
        },
        "ext_ratings": {
            "id": 294,
            "rating_avg": "4.6",
            "rating_count": 121
        },
        "user_ratings": [],
        "mensa": {
            "id": 10,
            "name": "Mensa am Ring",
            "city": "Münster",
            "street": "Domagkstr.",
            "houseNumber": "61",
            "zipCode": 48149,
            "startTime": "11:30:00",
            "endTime": "14:00:00"
        },
        "date": "2022-12-21",
        "priceStudent": "0.70",
        "priceEmployee": "1.05"
    },
    {
        "dish": {
            "id": 178,
            "categories": [],
            "additives": [],
            "allergies": [],
            "main": true,
            "name": "Pommes frites große Portion: 1,40€ / 2,10€",
            "url": "https://www.kochwiki.org/images/thumb/c/c4/H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg/1200px-H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg"
        },
        "ext_ratings": {
            "id": 294,
            "rating_avg": "4.6",
            "rating_count": 121
        },
        "user_ratings": [],
        "mensa": {
            "id": 10,
            "name": "Mensa am Ring",
            "city": "Münster",
            "street": "Domagkstr.",
            "houseNumber": "61",
            "zipCode": 48149,
            "startTime": "11:30:00",
            "endTime": "14:00:00"
        },
        "date": "2022-12-22",
        "priceStudent": "0.70",
        "priceEmployee": "1.05"
    },
    {
        "dish": {
            "id": 178,
            "categories": [],
            "additives": [],
            "allergies": [],
            "main": true,
            "name": "Pommes frites große Portion: 1,40€ / 2,10€",
            "url": "https://www.kochwiki.org/images/thumb/c/c4/H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg/1200px-H%C3%A4hnchenschenkel_mit_Pommes_Frites_01.jpg"
        },
        "ext_ratings": {
            "id": 294,
            "rating_avg": "4.6",
            "rating_count": 121
        },
        "user_ratings": [],
        "mensa": {
            "id": 10,
            "name": "Mensa am Ring",
            "city": "Münster",
            "street": "Domagkstr.",
            "houseNumber": "61",
            "zipCode": 48149,
            "startTime": "11:30:00",
            "endTime": "14:00:00"
        },
        "date": "2022-12-23",
        "priceStudent": "0.70",
        "priceEmployee": "1.05"
    }
]
```

### CODE REVIEW

**Comment by erikzimmermann** [comment]
Closes #142

**Review by martenjostmann — CHANGES_REQUESTED** [review]
Is it right that [0005_usercourse_alter_course_users.py](https://github.com/erikzimmermann/mensa-today/pull/164/files#diff-e9bb12c8c19bba334d01846d91c071f5e63e53d8a5e4749a06a45ee2eb909798),[0004_reservation_unique reservation.py](https://github.com/erikzimmermann/mensa-today/pull/164/files#diff-7b23cc29379b18b1c717884fbb840eda36f11ce8b31a8683c4a4956166f6d66e) and [0002_user_courses.py](https://github.com/erikzimmermann/mensa-today/pull/164/files#diff-09da1482e3cc6fbc43f53afc42322ca9d23831dc2a0df7885beb22e417375a94) are deleted. I guess they are important for updating the database on the server side

**Comment by erikzimmermann** [comment]
> Is it right that [0005_usercourse_alter_course_users.py](https://github.com/erikzimmermann/mensa-today/pull/164/files#diff-e9bb12c8c19bba334d01846d91c071f5e63e53d8a5e4749a06a45ee2eb909798),[0004_reservation_unique reservation.py](https://github.com/erikzimmermann/mensa-today/pull/164/files#diff-7b23cc29379b18b1c717884fbb840eda36f11ce8b31a8683c4a4956166f6d66e) and [0002_user_courses.py](https://github.com/erikzimmermann/mensa-today/pull/164/files#diff-09da1482e3cc6fbc43f53afc42322ca9d23831dc2a0df7885beb22e417375a94) are deleted. I guess they are important for updating the database on the server side

Well I now just deleted them in order to create proper initial migrations. But I can remove those and let you push them if you still have them.

**Comment by martenjostmann** [comment]
Yeah, I've added these in the last PR. So you can delete them now on your site.

**Review by lgiesen — CHANGES_REQUESTED** [review]
Should the migrations be in this commit? I thought we do not push them.

**Comment by erikzimmermann** [comment]
> Should the migrations be in this commit? I thought we do not push them.

They shouldn't be included as Marten already pushed them as initial migration in another branch. From now on, we'll push model changes as migrations to keep the compatibility with our host.

**Comment by lgiesen** [comment]
> 

Ok :) So change the merge conflicts and we are good to go, I guess :)

**Review by martenjostmann — APPROVED** [review]

**Pull request merged**
